# Generated by Django 3.2.6 on 2021-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Enter Name here', max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('year', models.CharField(choices=[('first', 'First'), ('second', 'Second')], max_length=255)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
